### ISSUE TITLE
Remove third-party WP plugins from your repo

### ISSUE THREAD

**Issue by mandiwise** [redacademy/tekera-spring-2017#4]
Third-party plugins have no place in your repo. Please .gitignore these, uncache the from your repo (you will need to make a commit to do this).

**Comment by kelfano** [comment]
Remove cyclone slider from github repo

**Commit no: 7ce6d83**

**Comment by rcass** [comment]
Just quick tip: If you do want to remember what third party plugins you are using in the project, the README is a great place to make such documentation ✍️  @kelfano
